# Dockerfile.nox
FROM ubuntu:24.04

LABEL author="Anderson Ignacio da Silva"
LABEL maintainer="anderson@aignacio.com"

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/Dublin

# Base + deps de build (inclui zlib1g-dev p/ FST/GTKWave do Verilator)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      tzdata ca-certificates curl wget git file make gcc g++ \
      perl python3 unzip zip time \
      autoconf automake libtool pkg-config help2man \
      flex bison ccache \
      libfl-dev zlib1g zlib1g-dev \
      libgoogle-perftools-dev numactl \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone \
    && rm -rf /var/lib/apt/lists/*

# --------------------------------------------------------------------------
# sv2v
# --------------------------------------------------------------------------
RUN wget -q https://github.com/zachjs/sv2v/releases/download/v0.0.11/sv2v-Linux.zip \
    && unzip -q sv2v-Linux.zip && rm sv2v-Linux.zip \
    && ln -s /sv2v-Linux/sv2v /usr/bin/sv2v && chmod +x /sv2v-Linux/sv2v

# --------------------------------------------------------------------------
# Verilator (tag estável p/ reprodutibilidade)
# --------------------------------------------------------------------------
ARG VERILATOR_REF=stable
RUN git clone --depth 1 --branch "$VERILATOR_REF" https://github.com/verilator/verilator.git /verilator
WORKDIR /verilator
RUN autoconf && \
    ./configure && \
    make -j"$(nproc)" && \
    make install && \
    cd / && rm -rf /verilator

# --------------------------------------------------------------------------
# RISC-V toolchain (xPack)
# --------------------------------------------------------------------------
WORKDIR /opt
RUN wget -qO- https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack/releases/download/v10.2.0-1.2/xpack-riscv-none-embed-gcc-10.2.0-1.2-linux-x64.tar.gz \
    | tar -xz && \
    ln -s /opt/xpack-riscv-none-embed-gcc-10.2.0-1.2/bin/riscv* /usr/bin

# --------------------------------------------------------------------------
# Sanity checks
# --------------------------------------------------------------------------
RUN sv2v --version || true && \
    verilator --version && \
    riscv-none-embed-gcc --version
